# Generated by Django 4.2.3 on 2023-07-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kotel_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kotel_id', models.IntegerField()),
                ('ugol_con', models.FloatField()),
                ('mazut_con', models.FloatField()),
                ('par', models.FloatField()),
                ('temp', models.FloatField()),
                ('pressure', models.FloatField()),
                ('goal_temp', models.FloatField()),
                ('time', models.FloatField()),
                ('parTotal', models.FloatField()),
                ('status', models.IntegerField()),
                ('f1', models.IntegerField()),
                ('f2', models.IntegerField()),
                ('f3', models.IntegerField()),
                ('f4', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='kotel_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kotel_id', models.IntegerField()),
                ('kotel_status', models.IntegerField()),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mazut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ugol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
