# Generated by Django 4.2.3 on 2023-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugol',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
